// GENERATED by tools/bake-text.mjs — do not edit. Re-bake: node tools/bake-text.mjs
// (TV1, 2026-10-06). What the runtime needs to use the three baked text textures in
// assets/dripping-pickle/text/: the glyph atlas's geometry and per-glyph cells, the ZOOM label rects,
// and the hashes of the inputs, so `node tools/bake-text.mjs --check` can say when a bake is stale.
export const TEXT_BAKE = { faceHash: '3c57469cd1f30d37', jarHash: '9f1918f1b3a84613' };

/** The glyph atlas (phosphor-sdf.ktx2). Distances to the skeleton, stored as 1 - d / range. */
export const PHOSPHOR = {"name":"Outpost Phosphor","atlasW":1024,"atlasH":560,"cellW":64,"cellH":80,"pxPerUnit":4,"range":3,"originX":12,"baseFromBottom":24,"cap":10,"xh":7,"desc":-3,"mono":{"capPerEm":0.571,"advancePerEm":0.6},"sans":{"capPerEm":0.717,"side":1.25,"space":3.6},"glyphs":{"0":[0,0,6.6],"1":[1,0,4],"2":[2,0,6.6],"3":[3,0,6.6],"4":[4,0,7],"5":[5,0,6.6],"6":[6,0,6.6],"7":[7,0,6.6],"8":[8,0,6.6],"9":[9,0,6.6]," ":[10,0,3.6],"A":[11,0,7],"B":[12,0,6.8],"C":[13,0,6.8],"D":[14,0,7],"E":[15,0,6.2],"F":[0,1,6],"G":[1,1,7],"H":[2,1,7],"I":[3,1,0],"J":[4,1,6],"K":[5,1,6.8],"L":[6,1,6],"M":[7,1,8],"N":[8,1,7],"O":[9,1,7],"P":[10,1,6.8],"Q":[11,1,7],"R":[12,1,6.8],"S":[13,1,6.6],"T":[14,1,7],"U":[15,1,7],"V":[0,2,7],"W":[1,2,9],"X":[2,2,7],"Y":[3,2,7],"Z":[4,2,7],"a":[5,2,6],"b":[6,2,6],"c":[7,2,5.8],"d":[8,2,6],"e":[9,2,6],"f":[10,2,5],"g":[11,2,6],"h":[12,2,6],"i":[13,2,0],"j":[14,2,3.6],"k":[15,2,5.8],"l":[0,3,0],"m":[1,3,8.4],"n":[2,3,6],"o":[3,3,6],"p":[4,3,6],"q":[5,3,6],"r":[6,3,4.4],"s":[7,3,5.6],"t":[8,3,5],"u":[9,3,6],"v":[10,3,6],"w":[11,3,8.4],"x":[12,3,6],"y":[13,3,6],"z":[14,3,6],".":[15,3,0],",":[0,4,0.9],":":[1,4,0],";":[2,4,0.9],"!":[3,4,0],"?":[4,4,6],"'":[5,4,0],"\"":[6,4,2.2],"’":[7,4,0.9],"‘":[8,4,0.9],"“":[9,4,2.6],"”":[10,4,2.6],"-":[11,4,4],"–":[12,4,6],"—":[13,4,9],"_":[14,4,7],"#":[15,4,7],"&":[0,5,7.2],"(":[1,5,1.5],")":[2,5,1.5],"[":[3,5,2.8],"]":[4,5,2.8],"{":[5,5,3.2],"}":[6,5,3.2],"/":[7,5,5],"\\":[8,5,5],"|":[9,5,0],"+":[10,5,6],"=":[11,5,6],"*":[12,5,5],"%":[13,5,7],"<":[14,5,6],">":[15,5,6],"^":[0,6,6],"~":[1,6,6.4],"`":[2,6,1.4],"@":[3,6,9.4],"$":[4,6,6.6],"·":[5,6,0],"°":[6,6,3],"§":[7,6,5.6]},"monoGlyphs":{"0":[8,6,6.6],"1":[9,6,5],"I":[10,6,4],"i":[11,6,4.8],"l":[12,6,4.8]}};

/** The ZOOM control's two labels (zoom-labels.ktx2): uv = [u0, v0, du, dv], v up; size in CSS px at dpr 1. */
export const PROMPT_LABELS = {"ZOOM IN ►":{"uv":[0,0.574074,0.941176,0.425926],"wCss":160,"hCss":46},"◄ ZOOM OUT":{"uv":[0,0.074074,1,0.425926],"wCss":170,"hCss":46}};

/** The jar label sheet (jar-labels.ktx2): the conveyor's cell grid, unchanged from the canvas it replaces. */
export const JAR_LABELS = { cols: 4, rows: 2, count: 8 };
